#pragma once
#include "NativeGameplayTags.h"

namespace ActionGameplayTags
{
	// Input Tags
	ACTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move)
	ACTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look)
	ACTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump)
	ACTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch)
	
	ACTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe)
	ACTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe)
	
	ACTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe)
	ACTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe)

	// Player tags
	ACTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe)
	
	ACTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe)
	ACTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe)
	
	ACTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe)
	ACTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe)
	
	ACTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe)
	ACTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axe)
	
	ACTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher)
}
